export const pages = [
  {
    path: '/ilias',
    author: 'Гомер',
    title: 'Илиада',
    year: 'IX-VIII до н.э.',
    language: 'Др-гр.',
    class: 'poesie',
  },
  {
    path: '/oedipus-tyrannos',
    author: 'Софокл',
    title: 'Царь Эдип',
    year: 'V до н.э.',
    language: 'Др-гр.',
    class: 'poesie',
  },
  {
    path: '/horace',
    author: 'Гораций',
    title: 'Оды',
    year: '23, 13 до н.э.',
    language: 'Др-гр.',
    class: 'poesie',
  },
  {
    path: '/levana',
    author: 'Де Квинси',
    title: 'Левана и Богородицы Скорби',
    year: '1845',
    language: 'Др-гр.',
    class: 'poesie',
  },
  {
    path: '/une-saison-en-enfer',
    author: 'Артюр Рембо',
    title: 'Одно лето в аду',
    year: '1873',
    language: 'Др-гр.',
    class: 'poesie',
  },
  {
    path: '/illuminations',
    author: 'Артюр Рембо',
    title: 'Озарения',
    year: '1873-1875, 1886',
    language: 'Др-гр.',
    class: 'poesie',
  },

  {
    path: '/heraclitus',
    author: 'Гераклит',
    title: 'Фрагменты',
    year: 'VI-V до н.э.',
    language: 'Др-гр.',
    class: 'philosophie',
  },
  {
    path: '/parmenides',
    author: 'Парменид',
    title: 'О природе',
    year: 'V до н.э.',
    class: 'philosophie',
  },
  {
    path: '/aristotle-metaphysica',
    author: 'Аристотель',
    title: 'Метафизика',
    year: 'IV до н.э.',
    class: 'philosophie',
  },
  {
    path: '/monadologie',
    author: 'Лейбниц',
    title: 'Монадология',
    year: '1714',
    class: 'philosophie',
  },
  {
    path: '/wer-denkt-abstract',
    author: 'Гегель',
    title: 'Кто мыслит абстрактно?',
    year: '1807',
    class: 'philosophie',
  },

  {
    path: '/schopenhauer-als-erzieher',
    author: 'Ницше',
    title: 'Шопенгауэр как воспитатель',
    year: '1874',
    class: 'nietzsche',
  },
  {
    path: '/menschliches-allzumenschliches',
    author: 'Ницше',
    title: 'Человеческое, слишком человеческое',
    year: '1878, 1886',
    class: 'nietzsche',
  },
  {
    path: '/gaya-scienza',
    author: 'Ницше',
    title: 'Весёлая наука',
    year: '1882, 1887',
    class: 'nietzsche',
  },
  {
    path: '/zarathustra',
    author: 'Ницше',
    title: 'Так говорил Заратустра',
    year: '1883-1885',
    class: 'nietzsche',
  },
  {
    path: '/jenseits-von-gut-und-boese',
    author: 'Ницше',
    title: 'По ту сторону добра и зла',
    year: '1886',
    class: 'nietzsche',
  },
  {
    path: '/goetzen-daemmerung',
    author: 'Ницше',
    title: 'Сумерки идолов',
    year: '1888',
    class: 'nietzsche',
  },
];
