function PlatoEuthyphroNumbers() {
  return (
    <>
      <p className='number'></p>
      <p className='number'>2a</p>
      <p className='number'>2b</p>
      <p className='number'>2c</p>
      <p className='number'>2d</p>
      <p className='number'>3a</p>
      <p className='number'>3b</p>
      <p className='number'>3c</p>
      <p className='number'>3d</p>
      <p className='number'>3e</p>
      <p className='number'>4a</p>
      <p className='number'>4b</p>
      <p className='number'>4c</p>
      <p className='number'>4d</p>
      <p className='number'>4e</p>
      <p className='number'>5a</p>
      <p className='number'>5b</p>
      <p className='number'>5c</p>
      <p className='number'>5d</p>
      <p className='number'>5e</p>
      <p className='number'>6a</p>
      <p className='number'>6b</p>
      <p className='number'>6c</p>
      <p className='number'>6d</p>
      <p className='number'>6e</p>
      <p className='number'>7a</p>
      <p className='number'>7b</p>
      <p className='number'>7c</p>
      <p className='number'>7d</p>
      <p className='number'>7e</p>
      <p className='number'>8a</p>
      <p className='number'>8b</p>
      <p className='number'>8c</p>
      <p className='number'>8d</p>
      <p className='number'>8e</p>
      <p className='number'>9a</p>
      <p className='number'>9b</p>
      <p className='number'>9c</p>
      <p className='number'>9d</p>
      <p className='number'>9e</p>
      <p className='number'>10a</p>
      <p className='number'>10b</p>
      <p className='number'>10c</p>
      <p className='number'>10d</p>
      <p className='number'>10e</p>
      <p className='number'>11a</p>
      <p className='number'>11b</p>
      <p className='number'>11c</p>
      <p className='number'>11d</p>
      <p className='number'>11e</p>
      <p className='number'>12a</p>
      <p className='number'>12b</p>
      <p className='number'>12c</p>
      <p className='number'>12d</p>
      <p className='number'>12e</p>
      <p className='number'>13a</p>
      <p className='number'>13b</p>
      <p className='number'>13c</p>
      <p className='number'>13d</p>
      <p className='number'>13e</p>
      <p className='number'>14a</p>
      <p className='number'>14b</p>
      <p className='number'>14c</p>
      <p className='number'>14d</p>
      <p className='number'>14e</p>
      <p className='number'>15a</p>
      <p className='number'>15b</p>
      <p className='number'>15c</p>
      <p className='number'>15d</p>
      <p className='number'>15e</p>
      <p className='number'>16a</p>
    </>
  );
}

export default PlatoEuthyphroNumbers;
