function MonadologieOriginal() {
    return (
      <><h2>La Monadologie (1714)<span className="popUp" id="cite_ref-1"><a href="#cite_note-1">1</a></span></h2>
      <h3>Thèses de Philosophie, ou Thèses rédigées en faveur du Prince Eugène</h3>
      <p>1. La Monade, dont nous parlerons ici, n’est autre chose qu’une substance simple, qui entre dans les composés&#160;; simple, c’est-à-dire sans parties. (<i><abbr className="abbr" title="Théodicée">Théod.</abbr></i>, § 10.)
      </p><p>2. Et il faut qu’il y ait des substances simples, puisqu’il y a des composés&#160;; car le composé n’est autre chose qu’un amas, ou <i><span className="lang-la" lang="la">aggregatum</span></i> des simples.
      </p><p>3. Or, là où il n’y a point de parties, il n’y a ni étendue, ni figure, ni divisibilité possible. Et ces monades sont les véritables Atomes de la nature, et en un mot les Éléments des choses.
      </p><p>4. Il n’y a aussi point de dissolution à craindre, et il n’y a aucune manière concevable par laquelle une substance simple puisse périr naturellement. (§ 80.)
      </p><p>5. Par la même raison il n’y en a aucune, par laquelle une substance simple puisse commencer naturellement, puisqu’elle ne saurait être formée par composition.
      </p><p>6. Ainsi on peut dire que les Monades ne sauraient commencer ni finir que tout d’un coup, c’est-à-dire elles ne sauraient commencer que par création, et finir que par annihilation&#160;; au lieu que ce qui est composé commence ou finit par parties.
      </p><p>7. Il n’y a pas moyen aussi d’expliquer comment une Monade puisse être altérée ou changée dans son intérieur par quelque autre créature, puisqu’on n’y saurait rien transposer, ni concevoir en elle aucun mouvement interne, qui puisse être excité, dirigé, augmenté ou diminué là dedans, comme cela se peut dans les composés, où il y a des changements entre les parties. Les Monades n’ont point de fenêtres, par lesquelles quelque chose y puisse entrer ou sortir. Les accidents ne sauraient se détacher, ni se promener hors des substances, comme faisaient autrefois les espèces sensibles des scolastiques. Ainsi ni substance, ni accident peut entrer de dehors dans une Monade.
      </p><p>8. Cependant il faut que les Monades aient quelques qualités, autrement ce ne seraient pas même des êtres. Et si les substances simples ne différaient point par leurs qualités, il n’y aurait pas de moyen de s’apercevoir d’aucun changement dans les choses, puisque ce qui est dans le composé ne peut venir que des ingrédients simples, et les monades étant sans qualités seraient indistinguables l’une de l’autre, puisqu’aussi bien elles ne diffèrent point en quantité&#160;: et par conséquent le plein étant supposé, chaque lieu ne recevrait toujours, dans le mouvement que l’Équivalent de ce qu’il avait eu, et un état des choses serait <i>indiscernable</i> de l’autre.
      </p><p>9. Il faut même, que chaque Monade soit différente de chaque autre. Car il n’y a jamais dans la nature, deux êtres, qui soient parfaitement l’un comme l’autre et où il ne soit possible de trouver une différence interne, ou fondée sur une dénomination intrinsèque.
      </p><p>10. Je prends aussi pour accordé que tout être créé est sujet au changement, et par conséquent la Monade créée aussi, et même que ce changement est continuel dans chacune.
      </p><p>11. Il s’ensuit de ce que nous venons de dire, que les changements naturels des monades viennent d’un principe interne, puisqu’une cause externe ne saurait influer dans son intérieur (§§ 396, 900)<span className="popUp" id="cite_ref-2"><a href="#cite_note-2">2</a></span>.
      </p><p>12. Mais il faut aussi qu’outre le principe du changement il y ait un <i>détail de ce qui change</i>, qui fasse pour ainsi dire la spécification et la variété des substances simples.
      </p><p>13. Ce détail doit envelopper une multitude dans l’unité ou dans le simple. Car tout changement naturel se faisant par degrés, quelque chose change et quelque chose reste&#160;; et par conséquent il faut que dans la substance simple il y ait une pluralité d’affections et de rapports, quoiqu’il n’y en ait point de parties.
      </p><p>14. L’état passager, qui enveloppe et représente une multitude dans l’unité ou dans la substance simple, n’est autre chose que ce qu’on appelle la <i>Perception</i>, qu’on doit distinguer de l’aperception ou de la conscience, comme il paraîtra dans la suite. Et c’est en quoi les cartésiens ont fort manqué, ayant compté pour rien les perceptions, dont on ne s’aperçoit pas. C’est aussi ce qui les a fait croire que les seuls Esprits étaient des Monades et qu’il n’y avait point d’Âmes des Bêtes ni d’autres Entéléchies, et qu’ils ont confondu avec le vulgaire un long étourdissement avec une mort à la rigueur, ce qui les a fait encore donner dans le préjugé scolastique des âmes entièrement séparées, et a même confirmé les esprits mal tournés dans l’opinion de la mortalité des âmes.
      </p><p>15. L’action du principe interne qui fait le changement ou le passage d’une perception à une autre, peut être appelé <i>Appétition</i>&#160;; il est vrai que l’appétit ne saurait toujours parvenir entièrement à toute la perception où il tend, mais il en obtient toujours quelque chose, et parvient à des perceptions nouvelles.
      </p><p>16. Nous expérimentons nous-mêmes une multitude dans la substance simple, lorsque nous trouvons que la moindre pensée dont nous nous apercevons enveloppe une variété dans l’objet. Ainsi tous ceux qui reconnaissent que l’âme est une substance simple doivent reconnaître cette multitude dans la Monade, et <abbr className="abbr" title="Monsieur">M.</abbr> Bayle ne devait point y trouver de la difficulté comme il a fait dans son Dictionnaire, article <i>Rorarius</i>.
      </p><p>17. On est obligé d’ailleurs de confesser que la <i>Perception</i> et ce qui en dépend est <i>inexplicable par des raisons mécaniques</i>, c’est-à-dire par les figures et par les mouvements. Et feignant qu’il y ait une machine, dont la structure fasse penser, sentir, avoir perception, on pourra la concevoir agrandie en conservant les mêmes proportions, en sorte qu’on y puisse entrer comme dans un moulin. Et cela posé, on ne trouvera en la visitant au dedans que des pièces qui poussent les unes les autres, et jamais de quoi expliquer une perception. Ainsi c’est dans la substance simple, et non dans le composé, ou dans la machine qu’il la faut chercher. Aussi n’y a-t-il que cela qu’on puisse trouver dans la substance simple, c’est-à-dire, les perceptions et leurs changements. C’est en cela seul aussi que peuvent consister toutes les <i>Actions internes</i> des substances simples (Préf., 2, 6).
      </p><p>18. On pourrait donner le nom d’Entéléchies à toutes les substances simples, ou monades créées, car elles ont en elles une certaine perfection (<span className="lang-grc" lang="grc">ἒχουσι τὸ ἐντελές</span>), il y a une suffisance (<span className="lang-grc" lang="grc">αὐτάρκεια</span>) qui les rend sources de leurs actions internes et pour ainsi dire des Automates incorporels.
      </p><p>19. Si nous voulons appeler âme tout ce qui a <i>Perceptions</i> et <i>Appétits</i> dans le sens général que je viens d’expliquer, toutes les substances simples ou Monades créées pourraient être appelées Âmes&#160;; mais, comme le sentiment est quelque chose de plus qu’une simple perception, je consens que le nom général de Monades et d’Entéléchies suffise aux substances simples qui n’auront que cela, et qu’on appelle âmes seulement celles dont la perception est plus distincte et accompagnée de mémoire.
      </p><p>20. Car nous expérimentons en nous-mêmes un état, où nous ne nous souvenons de rien et n’avons aucune perception distinguée, comme lorsque nous tombons en défaillance ou quand nous sommes accablés d’un profond sommeil sans aucun songe. Dans cet état l’âme ne diffère point sensiblement d’une simple monade&#160;; mais comme cet état n’est point durable, et qu’elle s’en tire, elle est quelque chose de plus (§ 64).
      </p><p>21. Et il ne s’ensuit point qu’alors la substance simple soit sans aucune perception. Cela ne se peut pas même par les raisons susdites&#160;; car elle ne saurait périr, elle ne saurait aussi subsister sans quelque affection, qui n’est autre chose que sa perception&#160;: mais quand il y a une grande multitude de petites perceptions, où il n’y a rien de distingué, on est étourdi&#160;; comme quand on tourne continuellement d’un même sens plusieurs fois de suite, ou il vient un vertige qui peut nous faire évanouir et qui ne nous laisse rien distinguer. Et la mort peut donner cet état pour un temps aux animaux.
      </p><p>22. Et comme tout présent état d’une substance simple est naturellement une suite de son état précédent, tellement que le présent y est gros de l’avenir (§ 360)&#160;;
      </p><p>23. Donc, puisque réveillé de l’étourdissement on <i>s’aperçoit</i> de ses perceptions, il faut bien qu’on en ait eu immédiatement auparavant, quoiqu’on ne s’en soit point aperçu&#160;; car une perception ne saurait venir naturellement que d’une autre perception, comme un mouvement ne peut venir naturellement que d’un mouvement (§§ 401, 403).
      </p><p>24. L’on voit par là que, si nous n’avions rien de distingué et pour ainsi dire de relevé, et d’un plus haut goût dans nos perceptions, nous serions toujours dans l’étourdissement. Et c’est l’état des Monades toutes nues. 
      </p><p>25. Aussi voyons-nous que la Nature a donné des perceptions relevées aux animaux, par les soins qu’elle a pris de leur fournir des organes, qui ramassent plusieurs rayons de lumière ou plusieurs ondulations de l’air, pour les faire avoir plus d’efficace par leur union. Il y a quelque chose d’approchant dans l’odeur, dans le goût et dans l’attouchement, et peut-être dans quantité d’autres sens, qui nous sont inconnus. Et j’expliquerai tantôt, comment ce qui se passe dans l’âme représente ce qui se fait dans les organes.
      </p><p>26. La mémoire fournit une espèce de consécution aux âmes, qui imite la raison, mais qui en doit être distinguée. C’est que nous voyons que les animaux, ayant la perception de quelque chose qui les frappe et dont ils ont eu perception semblable auparavant, s’attendent par la représentation de leur mémoire à ce qui y a été joint dans cette perception précédente et sont portés à des sentiments semblables à ceux qu’ils avaient pris alors. Par exemple&#160;: quand on montre le bâton aux chiens, ils se souviennent de la douleur qu’il leur a causée et crient et fuient (<abbr className="abbr" title="Préliminaires">Prélim.</abbr>, § 64)<span className="popUp" id="cite_ref-3"><a href="#cite_note-3">3</a></span>.
      </p><p>27. Et l’imagination forte qui les frappe et émeut, vient ou de la grandeur ou de la multitude des perceptions précédentes. Car souvent une impression forte fait tout d’un coup l’effet d’une longue habitude ou de beaucoup de perceptions médiocres réitérées.
      </p><p>28. Les hommes agissent comme les bêtes, en tant que les consécutions de leurs perceptions ne se font que par le principe de la mémoire&#160;; ressemblant aux médecins empiriques, qui ont une simple pratique sans théorie&#160;; et nous ne sommes qu’empiriques dans les trois quarts de nos actions. Par exemple, quand on s’attend qu’il y aura jour demain, on agit en empirique, parce que cela s’est toujours fait ainsi, jusqu’ici. Il n’y a que l’astronome qui le juge par raison.
      </p><p>29. Mais la connaissance des vérités nécessaires et éternelles est ce qui nous distingue des simples animaux et nous fait avoir la Raison et les sciences, en nous élevant à la connaissance de nous-mêmes et de Dieu. Et c’est ce qu’on appelle en nous Âme raisonnable, ou <i>Esprit</i>.
      </p><p>30. C’est aussi par la connaissance des vérités nécessaires et par leurs abstractions que nous sommes élevés aux actes réflexifs, qui nous font penser à ce qui s’appelle moi, et à considérer que ceci ou cela est en nous&#160;: et c’est ainsi qu’en pensant à nous, nous pensons à l’Être, à la Substance, au simple et au composé, l’immatériel et à Dieu même&#160;; en concevant que ce qui est borné en nous, est en lui sans bornes. Et ces actes réflexifs fournissent les objets principaux de nos raisonnements (<i><abbr className="abbr" title="Théodicée">Théod.</abbr></i>, <abbr className="abbr" title="Préface">Préf.</abbr>, 4, <i>a</i>).
      </p><p>31. Nos raisonnements sont fondés sur deux grands principes, <i>celui de la contradiction</i>, en vertu duquel nous jugeons faux ce qui en enveloppe, et vrai ce qui est opposé ou contradictoire au faux (§§ 44, 196.)
      </p><p>32. Et <i>celui de la raison suffisante</i>, en vertu duquel nous considérons qu’aucun fait ne saurait se trouver vrai ou existant, aucune énonciation véritable, sans qu’il y ait une raison suffisante, pourquoi il en soit ainsi et non pas autrement, quoique ces raisons le plus souvent ne puissent point nous être connues (§§ 44, 196.)
      </p><p>33. Il y a aussi deux sortes de vérités, celles de <i>Raisonnement</i> et celles de <i>Fait</i>. Les vérités de raisonnement sont nécessaires et leur opposé est impossible, et celles de fait sont contingentes et leur opposé est possible. Quand une vérité est nécessaire, on en peut trouver la raison par l’analyse, la résolvant en idées et en vérités plus simples, jusqu’à ce qu’on vienne aux primitives (§§&#160;170, 174, 189, 280, 282, 367. — <i>Abrégé</i>, <abbr className="abbr" title="object">obj.</abbr> 3.)
      </p><p>34. C’est ainsi que chez les mathématiciens, les <i>théorèmes</i> de spéculation et les <i>canons</i> de pratique sont réduits par l’analyse aux <i>Définitions</i>, <i>Axiomes</i> et <i>Demandes</i>.
      </p><p>35. Et il y a enfin des idées simples dont on ne saurait donner la définition&#160;; il y a aussi des axiomes et demandes, ou en un mot, des <i>principes primitifs</i>, qui ne sauraient être prouvés et n’en ont point besoin aussi, et ce sont les <i>énonciations identiques</i>, dont l’opposé contient une contradiction expresse (§§&#160;36, 37, 44, 45, 49, 52, 121, 122, 337, 340, 344.)
      </p><p>36. Mais la <i>raison suffisante</i> se doit trouver aussi dans les vérités <i>contingentes ou de fait</i>, c’est-à-dire, dans la suite des choses répandues par l’univers des créatures, où la résolution en raisons particulières pourrait aller à un détail sans bornes, à cause de la variété immense des choses de la nature et de la division des corps à l’infini. Il y a une infinité de figures et de mouvements présents et passés qui entrent dans la cause efficiente de mon écriture présente, et il y a une infinité de petites inclinations et dispositions de mon âme, présentes et passées, qui entrent dans la cause finale. 
      </p><p>37. Et comme tout ce détail n’enveloppe que d’autres contingents antérieurs ou plus détaillés, dont chacun a encore besoin d’une analyse semblable pour en rendre raison, on n’en est pas plus avancé, et il faut que la raison suffisante ou dernière soit hors de la suite ou <i>séries</i> de ce détail des contingences, quelque infini qu’il pourrait être.
      </p><p>38. Et c’est ainsi que la dernière raison des choses doit être dans une substance nécessaire, dans laquelle le détail des changements ne soit qu’éminemment, comme dans la source, et c’est ce que nous appelons <i>Dieu</i>. (§&#160;7.)
      </p><p>39. Or cette substance étant une raison suffisante de tout ce détail, lequel aussi est lié par tout, <i>il n’y a qu’un Dieu et ce Dieu suffit</i>.
      </p><p>40. On peut juger aussi que cette substance suprême qui est unique, universelle et nécessaire, n’ayant rien hors d’elle qui en soit indépendant, et étant une suite simple de l’être possible, doit être incapable de limites et contenir tout autant de réalité qu’il est possible.
      </p><p>41. D’où il s’ensuit que Dieu est absolument parfait&#160;; la perfection n’étant autre chose que la grandeur de la réalité positive prise précisément, en mettant à part les limites ou bornes dans les choses qui en ont. Et là, où il n’y a point de bornes, c’est-à-dire en Dieu, la perfection est absolument infinie. (§ 22. <abbr className="abbr" title="Préface">Préf.</abbr>, 4, <i>a</i>.)
      </p><p>42. Il s’ensuit aussi que les créatures ont leurs perfections de l’influence de Dieu, mais qu’elles ont leurs imperfections de leur nature propre incapable d’être sans bornes. Car c’est en cela qu’elles sont distinguées de Dieu. Cette <i>imperfection originale</i> des créatures se remarque dans l’inertie naturelle des corps (§§ 20, 27-30, 153, 167, 377 et suiv.)<span className="popUp" id="cite_ref-4"><a href="#cite_note-4">4</a></span>.
      </p><p>43. Il est vrai aussi qu’en Dieu est non seulement la source des existences, mais encore celle des essences, en tant que réelles, ou de ce qu’il y a de réel dans la possibilité. C’est parce que l’entendement de Dieu est la région des vérités éternelles ou des idées dont elles dépendent, et que sans lui il n’y aurait rien de réel dans les possibilités, et non seulement rien d’existant, mais encore rien de possible (§ 20.)
      </p><p>44. Car il faut bien que s’il y a une réalité dans les essences ou possibilités, ou bien dans les vérités éternelles, cette réalité soit fondée en quelque chose d’existant et d’actuel, et par conséquent dans l’existence de l’être nécessaire, dans lequel l’essence renferme l’existence, ou dans lequel il suffit d’être possible pour être actuel.
      </p><p>45. Ainsi Dieu seul ou l’Être nécessaire a ce privilège, qu’il faut qu’il existe, s’il est possible. Et comme rien ne peut empêcher la possibilité de ce qui n’enferme aucunes bornes, aucune négation, et par conséquence aucune contradiction, cela seul suffit pour connaître l’existence de Dieu <i>a priori</i>. Nous l’avons prouvée aussi par la réalité des vérités éternelles. Mais nous venons de la prouver aussi <i>a posteriori</i> puisque des êtres contingents existent, lesquels ne sauraient avoir leur raison dernière ou suffisante que dans l’être nécessaire, qui a la raison de son existence en lui-même.
      </p><p>46. Cependant il ne faut point s’imaginer avec quelques-uns, que les vérités éternelles, étant dépendantes de Dieu, sont arbitraires et dépendent de sa volonté, comme Descartes paraît l’avoir pris et puis <abbr className="abbr" title="Monsieur">M.</abbr> Poiret. Cela n’est véritable que des vérités contingentes, dont le principe est la <i>convenance</i> ou le choix <i>du meilleur</i>&#160;; au lieu, que les vérités nécessaires dépendent uniquement de son entendement, et en sont l’objet interne (§§ 180, 184, 185, 335, 351, 380.)
      </p><p>47. Ainsi Dieu seul est l’unité primitive, ou la substance simple originaire, dont toutes les monades créées ou dérivatives sont des productions, et naissent, pour ainsi dire, par des Fulgurations continuelles de la divinité de moment en moment, bornées par la réceptivité de la créature, à laquelle il est essentiel d’être limitée (§§ 382, 391, 398, 398.)
      </p><p>48. Il y a en Dieu la <i>Puissance</i>, qui est la source de tout, puis la <i>Connaissance</i>, qui contient le détail des idées, et enfin la <i>Volonté</i>, qui fait les changements ou productions selon le principe du meilleur. (§§ 7, 149, 150.) Et c’est ce qui répond à ce qui, dans les Monades créées, fait le sujet ou la base, la faculté perceptive et la faculté appétitive. Mais en Dieu ces attributs sont absolument infinis ou parfaits, et dans les monades créées ou dans les entéléchies ou <i><span className="lang-la" lang="la">perfectihabiis</span></i>, comme Hermolaus Barbarus traduisait ce mot, ce n’en sont que des imitations, à mesure qu’il y a de la perfection (§ 87).
      </p><p>49. La créature est dite <i>agir</i> au dehors en tant qu’elle a de la perfection, et <i>pâtir</i> d’une autre, en tant qu’elle est imparfaite. Ainsi l’on attribue l’action à la Monade en tant qu’elle a des perceptions distinctes, et la passion en tant qu’elle en a de confuses (§§ 32, 66, 386.)
      </p><p>50. Et une créature est plus parfaite qu’une autre en ce qu’on trouve en elle ce qui sert à rendre raison à priori de ce qui se passe dans l’autre, et c’est par là qu’on dit qu’elle agit sur l’autre.
      </p><p>51. Mais dans les substances simples ce n’est qu’une influence idéale d’une monade sur l’autre, qui ne peut avoir son effet que par l’intervention de Dieu, en tant que dans les idées de Dieu une monade demande avec raison que Dieu en réglant les autres dès le commencement des choses, ait égard à elle. Car, puisqu’une monade créée ne saurait avoir une influence physique sur l’intérieur de l’autre, ce n’est que par ce moyen que l’une peut avoir de la dépendance de l’autre (§§ 9, 54, 65, 66, 201. — <i>Abrégé</i>, obj. 3.)
      </p><p>52. Et c’est par là, qu’entre les créatures les actions et passions sont mutuelles. Car Dieu comparant deux substances simples, trouve en chacune des raisons qui l’obligent à y accommoder l’autre et par conséquent ce qui est <i>actif</i> à certains égards est passif suivant un autre point de considération&#160;: actif en tant que ce qu’on connaît distinctement en lui sert à rendre raison de ce qui se passe dans un autre&#160;; et <i>passif</i> en tant que la raison de ce qui se passe en lui se trouve dans ce qui se connaît distinctement dans un autre (§§ 66.)
      </p><p>53. Or, comme il y a une infinité des univers possibles dans les idées de Dieu et qu’il n’en peut exister qu’un seul, il faut qu’il y ait une raison suffisante du choix de Dieu, qui le détermine à l’un plutôt qu’à l’autre (§§ 8, 10, 44, 173, 196 et suiv., 225, 414, 416.)
      </p><p>54. Et, cette raison ne peut se trouver que dans la <i>convenance</i>, ou dans les degrés de perfection, que ces mondes contiennent, chaque possible ayant droit de prétendre à l’existence à mesure de la perfection qu’il enveloppe (§§ 84, 167, 350, 201, 130, 352, 343 et suiv., 354.)
      </p><p>55. Et c’est ce qui est la cause de l’existence du meilleur que la sagesse fait connaître à Dieu, que sa bonté le fait choisir, et que sa puissance le fait produire (§§ 8, 78, 80, 84, 119, 204, 206, 208. — <i>Abrégé</i>, obj., 1, 8.)
      </p><p>56. Or cette liaison ou cet accommodement de toutes les choses créées à chacune, et de chacune à toutes les autres, fait que chaque substance simple a des rapports qui expriment toutes les autres, et qu’elle est par conséquent un miroir vivant perpétuel de l’univers (§§ 130, 360.) 
      </p><p>57. Et comme une même ville regardée de différents côtés paraît toute autre et est comme multipliée perspectivement, il arrive de même que, par la multitude infinie des substances simples, il y a comme autant de différents univers, qui ne sont pourtant que les perspectives d’un seul selon les différents points de vue de chaque monade.
      </p><p>58. Et c’est le moyen d’obtenir autant de variété qu’il est possible, mais avec le plus grand ordre qui se puisse, c’est-à-dire c’est le moyen d’obtenir autant de perfection qu’il se peut (§§ 120, 124, 241, sqq., 214, 243, 275.)
      </p><p>59. Aussi n’est-ce que cette hypothèse (que j’ose dire démontrée) qui relève, comme il faut, la grandeur de Dieu&#160;; c’est ce que Monsieur Bayle reconnut, lorsque dans son Dictionnaire (article Rorarius) il y fit des objections, ou même il fut tenté de croire que je donnais trop à Dieu, et plus qu’il n’est possible. Mais il ne put alléguer aucune raison, pourquoi cette harmonie universelle, qui fait que toute substance exprime exactement toutes les autres par les rapports qu’elle y a, fût impossible.
      </p><p>60. On voit d’ailleurs dans ce que je viens de rapporter les raisons <i>a priori</i> pourquoi les choses ne sauraient aller autrement. Parce que Dieu en réglant le tout a eu égard à chaque partie, et particulièrement à chaque monade, dont la nature étant représentative, rien ne la saurait borner à ne représenter qu’une partie des choses&#160;; quoiqu’il soit vrai que cette représentation n’est que confuse dans le détail de tout l’univers, et ne peut être distincte que dans une petite partie des choses, c’est-à-dire, dans celles qui sont ou les plus prochaines ou les plus grandes par rapport à chacune des monades&#160;; autrement chaque monade serait une divinité. Ce n’est pas dans l’objet, mais dans la modification de la connaissance de l’objet, que les monades sont bornées. Elles vont toutes confusément à l’infini, au tout, mais elles sont limitées et distinguées par les degrés des perceptions distinctes.
      </p><p>61. Et les composés symbolisent en cela avec les simples. Car, comme tout est plein, ce qui rend toute la matière liée, et comme dans le plein tout mouvement fait quelque effet sur les corps distants à mesure de la distance, de sorte que chaque corps est affecté non seulement par ceux qui le touchent, et se ressent en quelque façon de tout ce qui leur arrive, mais aussi par leur moyen se ressent de ceux qui touchent les premiers dont il est touché  immédiatement&#160;: — il s’ensuit, que cette communication va à quelque distance que ce soit. Et par conséquent tout corps se ressent de tout ce qui se fait dans l’univers, tellement que celui qui voit tout pourrait lire dans chacun ce qui se fait partout et même ce qui s’est fait ou se fera, en remarquant dans le présent ce qui est éloigné, tant selon les temps que selon les lieux&#160;: <span className="lang-grc" lang="grc">σύμπνοια πάντα</span>, disait Hippocrate. Mais une âme ne peut lire en elle-même que ce qui y est représenté distinctement, elle ne saurait développer tout d’un coup tous ses replis, car ils vont à l’infini.
      </p><p>62. Ainsi quoique chaque monade créée représente tout l’univers, elle représente plus distinctement le corps qui lui est affecté particulièrement et dont elle fait l’entéléchie&#160;: et comme ce corps exprime tout l’univers par la connexion de toute la matière dans le plein, l’âme représente aussi tout l’univers en représentant ce corps, qui lui appartient d’une manière particulière (§ 400.)
      </p><p>63. Le corps appartenant à une monade, qui en est l’entéléchie ou l’âme, constitue avec l’entéléchie ce qu’on peut appeler un <i>vivant</i>, et avec l’âme ce qu’on appelle un <i>animal</i>. Or ce corps d’un vivant ou d’un animal est toujours organique, car toute monade étant un miroir de l’univers à sa mode, et l’univers étant réglé dans un ordre parfait, il faut qu’il y ait aussi un ordre dans le représentant, c’est-à-dire dans les perceptions de l’âme, et par conséquent dans le corps suivant lequel l’univers y est représenté. (§ 403.)
      </p><p>64. Ainsi chaque corps organique d’un vivant est une espèce de machine divine, ou d’un automate naturel, qui surpasse infiniment tous les automates artificiels. Parce qu’une machine, faite par l’art de l’homme, n’est pas machine dans chacune de ses parties. Par exemple, la dent d’une roue de laiton a des parties ou fragments, qui ne nous sont plus quelque chose d’artificiel et n’ont plus rien qui marque de la machine par rapport à l’usage où la roue était destinée. Mais les machines de la nature, c’est-à-dire les corps vivants, sont encore machines dans leurs moindres parties jusqu’à l’infini. C’est ce qui fait la différence entre la Nature et l’Art, c’est-à-dire, entre l’art divin et le nôtre (§§ 134, 146, 194, 483).
      </p><p>65. Et l’auteur de la nature a pu pratiquer cet artifice divin et infiniment merveilleux, parce que chaque portion de la matière n’est pas seulement divisible à l’infini, comme les anciens ont reconnu mais encore sous-divisée actuellement sans fin, chaque partie en parties, dont chacune a quelque mouvement propre&#160;: autrement il serait impossible, que chaque portion de la matière pût exprimer tout l’univers (Prélim. Discours, § 70. <i>Théod</i>. § 195.)
      </p><p>66. Par où l’on voit qu’il y a un monde de créatures, de vivants, d’animaux, d’entéléchies, d’âmes dans la moindre partie de la matière.
      </p><p>67. Chaque portion de la matière peut être conçue, comme un jardin plein de plantes, et comme un étang plein de poissons. Mais chaque rameau de la plante, chaque membre de l’animal, chaque goutte de ses humeurs est encore un tel jardin, ou un tel étang.
      </p><p>68. Et quoique la terre et l’air interceptés entre les plantes du jardin, ou l’eau interceptée entre les poissons de l’étang, ne soit point plante, ni poisson, ils en contiennent pourtant encore, mais le plus souvent d’une subtilité à nous imperceptible.
      </p><p>69. Ainsi il n’y a rien d’inculte, de stérile, de mort dans l’univers, point de chaos, point de confusion qu’en apparence&#160;; à peu près comme il en paraîtrait dans un étang, à une distance dans laquelle on verrait un mouvement confus et grouillement pour ainsi dire de poissons de l’étang, sans discerner les poissons mêmes (Préf. 5.)
      </p><p>70. On voit par là, que chaque corps vivant a une entéléchie dominante qui est l’âme dans l’animal&#160;; mais les membres de ce corps vivant sont pleins d’autres vivants, plantes, animaux, dont chacun a encore son entéléchie ou son âme dominante.
      </p><p>71. Mais il ne faut point s’imaginer avec quelques-uns, qui avaient mal pris ma pensée, que chaque âme a une masse ou portion de la matière propre ou affectée à elle pour toujours, et qu’elle possède par conséquent d’autres vivants inférieurs, destinés toujours à son service. Car tous les corps sont dans un flux perpétuel comme des rivières, et des parties y entrent et en en sortent continuellement.
      </p><p>72. Ainsi l’âme ne change de corps que peu à peu et par degrés, de sorte qu’elle n’est jamais dépouillée tout d’un coup de tous ses organes et il y a souvent métamorphose dans les animaux, mais jamais Métempsychose ni transmigration des âmes&#160;: il n’y a pas non plus des âmes tout à fait séparées, ni de Génies sans corps. Dieu seul en est détaché entièrement (§§ 90, 124).
      </p><p>73. C’est ce qui fait aussi qu’il n’y a jamais ni génération entière, ni mort parfaite prise à la rigueur, consistant dans la séparation de l’âme. Et ce que nous appelons <i>générations</i> sont des développements et des accroissements, comme ce que nous appelons <i>morts</i>, sont des enveloppements et des diminutions.
      </p><p>74. Les philosophes ont été fort embarrassés sur l’origine des formes, Entéléchies, ou Âmes&#160;: mais aujourd’hui, lorsqu’on s’est aperçu par des recherches exactes, faites sur les plantes, les insectes et les animaux, que les corps organiques de la nature ne sont jamais produits d’un chaos ou d’une putréfaction, mais toujours par des semences dans lesquelles il y avait sans doute quelque <i>préformation</i>, on a jugé que non seulement le corps organique y était déjà avant la conception, mais encore une âme dans ce corps, et en un mot l’animal même, et que par le moyen de la conception cet animal a été seulement disposé à une grande transformation pour devenir un animal d’une autre espèce. On voit même quelque chose d’approchant hors de la génération, comme lorsque les vers deviennent mouches et que les chenilles deviennent papillons, (§§ 88, 89, <abbr className="abbr" title="Préface">Préf.</abbr> 5 sqq., §§ 90, 187-188, 403, 86, 397.)
      </p><p>75. Les animaux, dont quelques-uns sont élevés au degré des plus grands animaux par le moyen de la conception, peuvent être appelés <i>spermatiques</i>&#160;; mais ceux d’entre eux, qui demeurent dans leur espèce, c’est-à-dire la plupart, naissent, se multiplient et sont détruits comme les grands animaux, et il n’y a qu’un petit nombre d’élus, qui passe à un plus grand théâtre.
      </p><p>76. Mais ce n’était que la moitié de la vérité&#160;: j’ai donc jugé que, si l’animal ne commence jamais naturellement, il ne finit pas naturellement non plus &#160;; et que non seulement il n’y aura point de génération, mais encore point de destruction entière ni mort prise à la rigueur. Et ces raisonnements faits <i>a posteriori</i> et tirés des expériences s’accordent parfaitement avec mes principes déduits <i>a priori</i> comme ci-dessus (§ 90.)
      </p><p>77. Ainsi on peut dire que non seulement l’âme (miroir d’un univers indestructible) est indestructible, mais encore l’animal même, quoique sa machine périsse souvent en partie, et quitte ou prenne des dépouilles organiques.
      </p><p>78. Ces principes m’ont donné moyen d’expliquer naturellement l’union, ou bien la conformité de l’âme et du corps organique. L’âme suit ses propres lois, et le corps aussi les siennes&#160;; et ils se rencontrent en vertu de l’harmonie préétablie entre toutes les substances, puisqu’elles sont toutes les représentations d’un même univers. (<abbr className="abbr" title="Préface">Préf.</abbr>, §6&#160;; <i>Théod.</i> 340, 352, 353, 358.)
      </p><p>79. Les âmes agissent selon les lois des causes finales par appétitions, fins et moyens. Les corps agissent selon les lois des causes efficientes ou des mouvements. Et les deux règnes, celui des causes efficientes et celui des causes finales sont harmoniques entre eux.
      </p><p>80. Descartes a reconnu que les âmes ne peuvent point donner de la force aux corps, parce qu’il y a toujours la même quantité de force dans la matière. Cependant il a cru que l’âme pouvait changer la direction des corps. Mais c’est parce qu’on n’a point su de son temps la loi de la nature, qui porte encore la conservation de la même direction totale dans la matière. S’il l’avait remarquée, il serait tombé dans mon système de l’harmonie préétablie (<abbr className="abbr" title="Préface">Préf.</abbr>, §§ 22, 59, 60, 61, 62, 66, 345, 346 sqq., 354, 355).
      </p><p>81. Ce système fait que les corps agissent comme si (par impossible) il n’y avait point d’âmes, et que les âmes agissent comme s’il n’y avait point de corps, et que tous deux agissent comme si l’un influait sur l’autre.
      </p><p>82. Quant aux esprits ou âmes raisonnables, quoique je trouve qu’il y a dans le fond la même chose dans tous les vivants et animaux, comme nous venons de dire (savoir que l’animal et l’âme ne commencent qu’avec le monde, et ne finissent pas non plus que le monde), — il y a pourtant cela de particulier dans les animaux raisonnables, que leurs petits animaux spermatiques, tant qu’ils ne sont que cela, ont seulement des âmes ordinaires ou sensitives mais dès que ceux qui sont élus, pour ainsi dire, parviennent par une actuelle conception à la nature humaine, leurs âmes sensitives sont élevées au degré de la raison et à la prérogative des esprits (§§ 91, 397.)
      </p><p>83. Entre autres différences qu’il y a entre les âmes ordinaires et les esprits, dont j’en ai déjà marqué une partie, il y a encore celle-ci que les âmes en général sont des miroirs vivants ou images de l’univers des créatures, mais que les esprits sont encore des images de la Divinité même, ou de l’Auteur même de la nature, capables de connaître le système de l’univers et d’en imiter quelque chose par des échantillons architectoniques, chaque esprit étant comme une petite divinité dans son département (§ 147.)
      </p><p>84. C’est ce qui fait que les esprits sont capables d’entrer dans une manière de société avec Dieu, et qu’il est à leur égard non seulement ce qu’un inventeur est à sa machine (comme Dieu l’est par rapport aux autres créatures), mais encore ce qu’un prince est à ses sujets, et même un père à ses enfants.
      </p><p>85. D’où il est aisé de conclure que l’assemblage de tous les esprits doit composer la cité de Dieu c’est-à-dire le plus parfait état qui soit possible sous le plus parfait des monarques (<i>Abrégé</i>, obj.). 
      </p><p>86. Cette cité de Dieu, cette monarchie véritablement universelle, est un monde moral, dans le monde naturel, et ce qu’il y a de plus élevé et de plus divin dans les ouvrages de Dieu, et c’est en lui que consiste véritablement la gloire de Dieu, puisqu’il n’y en aurait point si sa grandeur et sa bonté n’étaient pas connues et admirées par les esprits&#160;: c’est aussi par rapport à cette cité divine qu’il a proprement de la bonté, au lieu que sa sagesse et sa puissance se montrent partout.
      </p><p>87. Comme nous avons établi ci-dessus une harmonie parfaite entre deux règnes naturels, l’un des causes efficientes, l’autre des finales, nous devons remarquer ici encore une autre harmonie entre le règne physique de la nature et le règne moral de la grâce, c’est-à-dire entre Dieu considéré comme architecte de la machine de l’univers, et Dieu considéré comme monarque de la cité divine des esprits (§§ 62, 74, 118, 248, 112, 130, 247.)
      </p><p>88. Cette Harmonie fait que les choses conduisent à la grâce par les voies mêmes de la nature, et que ce globe par exemple doit être détruit et réparé par les voies naturelles dans les moments que le demande le gouvernement des esprits pour le châtiment des uns et la récompense des autres (§§ 18 sqq., 110, 244-245, 340.)
      </p><p>89. On peut dire encore, que Dieu comme architecte contente en tout Dieu comme législateur, et qu’ainsi les péchés doivent porter leur peine avec eux par l’ordre de la nature, et en vertu même de la structure mécanique des choses, et que de même les belles actions s’attireront leurs récompenses par des voies machinales par rapport aux corps, quoique cela ne puisse et ne doive pas arriver toujours sur-le-champ.
      </p><p style={{ borderBottom: 'none', paddingBottom: 6 }}>90. Enfin sous ce gouvernement parfait il n’y aurait point de bonne action sans récompense, point de mauvaise sans châtiment, et tout doit réussir au bien des bons, c’est-à-dire de ceux qui ne sont point des mécontents dans ce grand état, qui se fient à la providence, après avoir fait leur devoir, et qui aiment et imitent, comme il faut, l’auteur de tout bien, se plaisant dans la considération de ses perfections suivant la nature du <i>pur amour</i> véritable, qui fait prendre plaisir à la félicité de ce qu’on aime. C’est ce qui fait travailler les personnes sages et vertueuses à tout ce qui paraît conforme à la volonté divine présomptive, ou antécédente, et se contenter cependant de ce que Dieu fait arriver effectivement par sa volonté secrète, conséquente et décisive, en reconnaissant que, si nous pouvions entendre assez l’ordre de l’univers, nous trouverions qu’il surpasse tous les souhaits les plus sages, et qu’il est impossible de le rendre meilleur qu’il est, non seulement pour le tout en général, mais encore pour nous-mêmes en particulier, si nous sommes attachés comme il faut à l’auteur du tout, non seulement comme à l’architecte et à la cause efficiente de notre être, mais encore comme à notre Maître et à la cause finale qui doit faire tout le but de notre volonté, et peut seul faire notre bonheur (<abbr className="abbr" title="Préface">Préf.</abbr> 4, § 278.)
      </p>
      <p className="annoContent">
      <a href="#cite_ref-1" id="cite_note-1">1</a> <span className="reference-text">Nous donnons ici le texte de la Monadologie d’après l’édition de <abbr className="abbr" title="Monsieur">M.</abbr> Émile Boutroux qui a compulsé le manuscrit autographe de Leibniz à la Bibliothèque de Hanovre, ainsi que deux copies, revues et corrigées par Leibniz lui-même.</span>
      <br className="bigBlank" />
      <a href="#cite_ref-2" id="cite_note-2">2</a> <span className="reference-text">Renvois à la <i>Théodicée</i>.</span>
      <br className="bigBlank" />
      <a href="#cite_ref-3" id="cite_note-3">3</a> <span className="reference-text">Ces Préliminaires sont l’Introduction de la <i>Théodicée</i>&#160;: «&#160;Discours sur la Conformité de la Foi avec la Raison.&#160;»</span>
      <br className="bigBlank" />
      <a href="#cite_ref-4" id="cite_note-4">4</a> <span className="reference-text">Ce dernier membre de phrase manque dans le manuscrit autographe, mais a été ajouté par Leibniz dans l’une des copies.</span></p></>
    )
  }
  
  export default MonadologieOriginal